### ISSUE TITLE
Read from multiple queues

### ISSUE THREAD

**Issue by hep-ml** [DUNE-DAQ/triggermodules#1]
The modules that read in queues as sources shall be able to so from multiple sources (`1-to-N` schema).
This feature is required for the MLT.

**Comment by plasorak** [comment]
Since the whole information (TP, TA, TC) passing is going to evolve quite dramatically soon, I dont think this is a very interesting project. I think we should focus on single producer, single consumer queues for now and make sure the machinery works. Then we can focus on using IPM to pass the object around and merge/window them.

**Comment by hep-ml** [comment]
Ok, I see. I was unaware of the foreseen changes. Are there any documents/intros on IPM?

**Comment by georgiak** [comment]
The N-to-1 mapping is a fundamental function of the DS modules, so I think we should prioritize it. I don't see how we can test the module-wide or multiple-APA Trigger Candidate generation or MLT in any other way. The 1-to-1 functionality is there, more or less, so I think N-to-1 is the next highest priority. What exactly are you referring to, @plasorak, when you say the whole information passing is going to evolve quite dramatically?

**Comment by plasorak** [comment]
I think that's going to be next iteration of the appfwk, if I remember what Kurt was saying. There is a new repo here: https://github.com/DUNE-DAQ/ipm which I was told is what will be used in the end. Hence my comment about the MPMC queues. Note these don't do any time windowing that will be required in the final system.

**Comment by hep-ml** [comment]
Yes, this is quite a dramatical change. This would also affect the `triggermodules`, and how `moo` config/`jsonnet` works. However I see that the system with subscription makes N-to-N queues much easier.
So, how should we proceed? Does it make sense to already start the upgrade process?

**Comment by hep-ml** [comment]
And do you have an idea when v2.3 would be released?

**Comment by plasorak** [comment]
I'd hold off until we are told to start using it.

**Comment by hep-ml** [comment]
I'm trying to figure out whether we should implement N-to-1 now, which only makes sense if there is considerable amount of time until `ipm` gets released, or whether we should for `v2.3`. I will investigate with Phil about the timeline.

**Comment by hep-ml** [comment]
Apparently ipm v1.0.0 has been released with dunedaq-v2.2.0.

**Comment by hep-ml** [comment]
Actually writing from multiple plugins to a single queue was much easier to implement than having a plugin reading from multiple queues, while both complete the same task.

**Comment by hep-ml** [comment]
Received data from multiple sources – verified.
