### ISSUE TITLE
Redefine data format

### ISSUE THREAD

**Issue by hep-ml** [DUNE-DAQ/triggermodules#2]
Redefine TP/TA/TC/TD data formats after discussion on them have been carried out

**Comment by plasorak** [comment]
Agreed. For the TD I don't think we can do that unless we have a discussion with DataFlow and what they actually need. Maybe that is already in an interface document on docdb.

**Comment by hep-ml** [comment]
We are in touch with Upstream DAQ for the TDs. They promised to deliver specifications this week.

**Comment by hep-ml** [comment]
(see also https://github.com/DUNE-DAQ/triggermodules/issues/6)

**Comment by hep-ml** [comment]
Upgrade completed `triggeralgs` under branch `dataproductrevision`. With timestamps in branch `timing`. `triggermodules` pending.

**Comment by hep-ml** [comment]
Also done for `triggermodules`, compiled and tested with 1-to-N app.
